name: Build libchams

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NDK r25c
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: true

      - name: Build
        run: |
          cd jni
          $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=.. APP_BUILD_SCRIPT=Android.mk NDK_APPLICATION_MK=Application.mk -j4

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libchams
          path: libs/armeabi-v7a/libchams.so
